version: "3"
services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    links:
      - "mongo:mongo"
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password123@mongo:27017/
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
  mongo:
    image: mongo:4.4.14-focal